name: flutter_cash_drawer
description: Плагин для открытия денежного ящика по USB через ESC-команду. Работает на Windows.
version: 1.0.0
repository: https://github.com/your_username/flutter_cash_drawer

environment:
  sdk: ^3.6.1
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  plugin:
    platforms:
      windows:
        pluginClass: FlutterCashDrawerPluginCApi